"""initial_schema

Revision ID: 52b48ded5bbd
Revises: 
Create Date: 2026-07-12 14:10:58.894722

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52b48ded5bbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("name IN ('Fleet_Manager', 'Dispatcher', 'Safety_Officer', 'Financial_Analyst')", name='check_role_name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("email LIKE '%%@%%'", name='check_email_format'),
    sa.CheckConstraint('LENGTH(password_hash) >= 60', name='check_password_hash_length'),
    sa.CheckConstraint('LENGTH(username) >= 3', name='check_username_length'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('drivers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'OFF_DUTY', 'SUSPENDED', name='driverstatus'), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('license_expiry > hire_date', name='check_license_expiry_after_hire'),
    sa.CheckConstraint('safety_score >= 0 AND safety_score <= 100', name='check_safety_score_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_created_by'), 'drivers', ['created_by'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_is_active'), 'drivers', ['is_active'], unique=False)
    op.create_index(op.f('ix_drivers_license_expiry'), 'drivers', ['license_expiry'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_entity_type'), 'events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_performed_by'), 'events', ['performed_by'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'IN_SHOP', 'RETIRED', name='vehiclestatus'), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fuel_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('acquisition_cost >= 0', name='check_acquisition_cost_positive'),
    sa.CheckConstraint('capacity_kg > 0', name='check_capacity_positive'),
    sa.CheckConstraint('fuel_efficiency IS NULL OR fuel_efficiency > 0', name='check_fuel_efficiency_positive'),
    sa.CheckConstraint('health_score >= 0 AND health_score <= 100', name='check_health_score_range'),
    sa.CheckConstraint('year >= 1900 AND year <= EXTRACT(YEAR FROM NOW()) + 1', name='check_vehicle_year'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_created_by'), 'vehicles', ['created_by'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_is_active'), 'vehicles', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('driver_documents',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("document_type IN ('license', 'medical_certificate')", name='check_driver_document_type'),
    sa.CheckConstraint('expiry_date > created_at::date', name='check_expiry_after_creation'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_documents_document_type'), 'driver_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_driver_documents_driver_id'), 'driver_documents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_documents_expiry_date'), 'driver_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_driver_documents_id'), 'driver_documents', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('expense_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("expense_type IN ('tolls', 'repairs', 'other')", name='check_expense_type'),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_type'), 'expenses', ['expense_type'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_vehicle_id'), 'expenses', ['vehicle_id'], unique=False)
    op.create_table('fuel_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('quantity_liters', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odometer_reading', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cost > 0', name='check_cost_positive'),
    sa.CheckConstraint('cost_per_unit > 0', name='check_cost_per_unit_positive'),
    sa.CheckConstraint('odometer_reading > 0', name='check_odometer_positive'),
    sa.CheckConstraint('quantity_liters > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_logs_id'), 'fuel_logs', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_logs_vehicle_id'), 'fuel_logs', ['vehicle_id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='maintenancestatus'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("maintenance_type IN ('Scheduled', 'Breakdown', 'Inspection')", name='check_maintenance_type'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at > created_at', name='check_completed_after_created'),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name='check_cost_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_created_by'), 'maintenance_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_scheduled_date'), 'maintenance_logs', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_status'), 'maintenance_logs', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_vehicle_id'), 'maintenance_logs', ['vehicle_id'], unique=False)
    op.create_table('trips',
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cargo_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cargo_description', sa.Text(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DISPATCHED', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cargo_weight_kg > 0', name='check_cargo_weight_positive'),
    sa.CheckConstraint('completed_at IS NULL OR dispatched_at IS NULL OR completed_at > dispatched_at', name='check_completed_after_dispatched'),
    sa.CheckConstraint('dispatched_at IS NULL OR dispatched_at > created_at', name='check_dispatched_after_created'),
    sa.CheckConstraint('distance_km > 0', name='check_distance_positive'),
    sa.CheckConstraint('revenue IS NULL OR revenue >= 0', name='check_revenue_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_completed_at'), 'trips', ['completed_at'], unique=False)
    op.create_index(op.f('ix_trips_created_by'), 'trips', ['created_by'], unique=False)
    op.create_index(op.f('ix_trips_dispatched_at'), 'trips', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('vehicle_documents',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("document_type IN ('insurance', 'permit', 'fitness_certificate', 'puc')", name='check_vehicle_document_type'),
    sa.CheckConstraint('expiry_date > created_at::date', name='check_expiry_after_creation'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_documents_document_type'), 'vehicle_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_expiry_date'), 'vehicle_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_id'), 'vehicle_documents', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_id'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_expiry_date'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_document_type'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_dispatched_at'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_by'), table_name='trips')
    op.drop_index(op.f('ix_trips_completed_at'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_maintenance_logs_vehicle_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_status'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_scheduled_date'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_created_by'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_fuel_logs_vehicle_id'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_id'), table_name='fuel_logs')
    op.drop_table('fuel_logs')
    op.drop_index(op.f('ix_expenses_vehicle_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_type'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_driver_documents_id'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_expiry_date'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_driver_id'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_document_type'), table_name='driver_documents')
    op.drop_table('driver_documents')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_is_active'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_by'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_events_performed_by'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_expiry'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_is_active'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_created_by'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
